version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'docker'
    ports:
      - '5432:5432'


  app:
    build:
      context: .  
      # target: ingles

    command: >
      bash -c '
        sleep 5
        python3 models.py
        python3 launch.py
      '
    ports:
      - '5000:5000'
    
    working_dir: /app/
    
    links:
      - postgres
    volumes:
      - ./:/app
